name: 21.2 - Managing Concurrency at Job Level

on:
    workflow_dispatch:

    
jobs:
    ping-with-concurrency:
        runs-on: ubuntu-latest
        concurrency: 
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6
            - name: Ping URL
              uses: ./.github/actions/docker-ping-url
              id: ping_url
              with:
                url: https://invalid.url.test'
                max_trials: 20  
                delay: 5
    ping-without-concurrency:
        runs-on: ubuntu-latest
       
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6
            - name: Ping URL
              uses: ./.github/actions/docker-ping-url
              id: ping_url
              with:
                url: https://invalid.url.test'
                max_trials: 20  
                delay: 5